services:
  # python:3.13
  python:
    pull_policy: missing
    image: python:3.13
  # dalia
  dalia:
    depends_on:
      - python
    pull_policy: never
    ports:
      - "8118:8118"
    restart: always
    container_name: dalia
    image: dalia
    build: 
      context: .
      dockerfile: dockerfile
    environment:
      - docker=true
    volumes:
      - ${sicstus}:/sicstus
      - ${src}:/src
      - ${dali}:/dali
    networks:
      - DALIA
networks:
  DALIA:
    driver: bridge